include: package:lints/recommended.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    - avoid_print
    - use_key_in_widget_constructors
    - prefer_const_constructors
    - prefer_const_declarations
