name: code_sync
description: A new Flutter project.
publisn_to: 'none'
version: 0.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.6.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.1.0
  logger: ^2.5.0
  flutter_neumorphic_plus: ^3.4.0
  http: ^1.5.0
  shared_preferences: ^2.5.3
  build_runner: ^2.6.1
  intl: ^0.20.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.1.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/bg_fon.png
    - assets/memoji.webp
  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/sanFran/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/sanFran/SF-Pro-Display-Bold.otf
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon_apps.png"
